version: "3.9"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
            ports: ["0:8080"] # Dynamically map a random host port to the container's assigned port
            environment:
                SPRING_REDIS_HOST: redis
                SPRING_REDIS_PORT: 6379

    redis:
        image: redis:latest
        ports: ["6379:6379"]
